/**
 * Exhaustive individual product data for SourceKart India.
 * Each product has its own page route, CAS number, description, and image.
 */

export type IndividualProduct = {
  slug: string;
  name: string;
  cas: string;
  categorySlug: string;
  categoryTitle: string;
  description: string;
  applications: string[];
};

export const individualProducts: IndividualProduct[] = [
  // === AMINO ACIDS (41 products) ===
  { slug: "glycine", name: "Glycine", cas: "56-40-6", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "The simplest amino acid, used in food, pharma, and animal nutrition as a flavour enhancer, buffering agent, and glycine premix base.", applications: ["pharmaceuticals", "animal-nutrition"] },
  { slug: "l-alanine", name: "L-Alanine", cas: "56-41-7", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A non-essential amino acid used in sports nutrition, clinical nutrition, and food processing for its sweet taste and metabolic role.", applications: ["sports-nutrition", "pharmaceuticals"] },
  { slug: "l-arginine-aspartate", name: "L-Arginine Aspartate", cas: "7675-85-4", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A salt of L-arginine with aspartic acid, used in sports supplements for nitric oxide support and ammonia buffering.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "l-arginine-hcl", name: "L-Arginine HCL", cas: "1119-34-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Arginine hydrochloride, a key ingredient in pre-workout formulas and cardiovascular support supplements.", applications: ["sports-nutrition", "nutraceuticals", "pharmaceuticals"] },
  { slug: "l-arginine-nitrate", name: "L-Arginine Nitrate", cas: "743-73-3", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Arginine nitrate, used in sports nutrition for enhanced nitric oxide production and vasodilation.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "l-asparagine-monohydrate", name: "L-Asparagine Monohydrate", cas: "5794-13-8", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An amino acid involved in protein synthesis and ammonia metabolism, used in clinical nutrition and pharma.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "l-aspartic-acid", name: "L-Aspartic Acid", cas: "56-84-8", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A non-essential amino acid used in sports nutrition, food processing, and as a precursor for other amino acids.", applications: ["sports-nutrition", "pharmaceuticals"] },
  { slug: "l-carnitine-fumarate", name: "L-Carnitine Fumarate", cas: "90471-79-7", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Carnitine fumarate salt used for energy metabolism support in sports nutrition and weight management formulas.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "l-carnitine-hcl", name: "L-Carnitine HCL", cas: "66-19-5", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Carnitine hydrochloride, supports fatty acid oxidation and energy production in metabolic and sports supplements.", applications: ["sports-nutrition", "nutraceuticals", "pharmaceuticals"] },
  { slug: "l-carnitine-tartrate", name: "L-Carnitine Tartrate", cas: "36687-82-8", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Carnitine tartrate, the most bioavailable carnitine form, used in premium sports recovery and fat metabolism products.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "l-cysteine-base", name: "L-Cysteine Base", cas: "52-90-4", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A sulfur-containing amino acid used as a dough conditioner, antioxidant, and precursor to glutathione.", applications: ["pharmaceuticals"] },
  { slug: "l-cysteine-hcl", name: "L-Cysteine HCL", cas: "52-89-1", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Cysteine hydrochloride monohydrate, used in pharmaceuticals, food processing, and as a mucolytic agent.", applications: ["pharmaceuticals"] },
  { slug: "l-cystine", name: "L-Cystine", cas: "56-89-3", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A dimeric amino acid with two cysteine residues, used in hair and skin health supplements and pharmaceutical synthesis.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "l-glutamic-acid", name: "L-Glutamic Acid", cas: "56-86-0", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A key excitatory neurotransmitter amino acid used in food flavouring, pharma, and as a chelating agent.", applications: ["pharmaceuticals", "industrial-chemicals"] },
  { slug: "l-histidine-base", name: "L-Histidine Base", cas: "71-00-1", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An essential amino acid important for histamine production, metal binding, and pH buffering in pharmaceuticals.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "l-histidine-hcl", name: "L-Histidine HCL", cas: "5934-29-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Histidine hydrochloride monohydrate, used in clinical nutrition, IV formulations, and specialty supplements.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "l-isoleucine", name: "L-Isoleucine", cas: "73-32-5", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A branched-chain amino acid essential for muscle protein synthesis and energy regulation during exercise.", applications: ["sports-nutrition", "animal-nutrition", "nutraceuticals"] },
  { slug: "l-leucine", name: "L-Leucine", cas: "61-90-5", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "The most potent BCAA for triggering muscle protein synthesis, widely used in sports and clinical nutrition.", applications: ["sports-nutrition", "nutraceuticals", "animal-nutrition"] },
  { slug: "l-lysine-acetate", name: "L-Lysine Acetate", cas: "57282-49-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Lysine acetate salt used in animal feed and human nutrition for growth support and collagen synthesis.", applications: ["animal-nutrition", "nutraceuticals"] },
  { slug: "l-lysine-base", name: "L-Lysine Base", cas: "56-87-1", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An essential amino acid critical for protein synthesis, calcium absorption, and immune function support.", applications: ["animal-nutrition", "nutraceuticals", "pharmaceuticals"] },
  { slug: "l-lysine-hcl", name: "L-Lysine HCL", cas: "657-27-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Lysine hydrochloride, the most common commercial form used in feed, food fortification, and supplements.", applications: ["animal-nutrition", "nutraceuticals"] },
  { slug: "l-malic-acid", name: "L-Malic Acid", cas: "6915-15-7", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An organic acid used as a flavour enhancer, acidulant, and metabolic intermediate in sports nutrition.", applications: ["sports-nutrition", "pharmaceuticals"] },
  { slug: "l-methionine", name: "L-Methionine", cas: "63-68-3", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A sulfur-containing essential amino acid critical for protein synthesis, methylation, and antioxidant production.", applications: ["animal-nutrition", "pharmaceuticals", "nutraceuticals"] },
  { slug: "l-norvaline", name: "L-Norvaline", cas: "6600-40-4", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A non-proteinogenic amino acid used in research and specialty sports supplements for arginase inhibition.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "l-ornithine-alpha-ketoglutarate", name: "L-Ornithine Alpha Ketoglutarate", cas: "5191-97-9", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Ornithine AKG complex used in clinical nutrition for wound healing, liver support, and muscle recovery.", applications: ["pharmaceuticals", "nutraceuticals", "sports-nutrition"] },
  { slug: "l-ornithine-hcl", name: "L-Ornithine HCL", cas: "3184-13-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "L-Ornithine hydrochloride used in liver health supplements and urea cycle support formulations.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "l-ornithine-l-aspartate", name: "L-Ornithine L-Aspartate", cas: "3230-94-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A combination amino acid used in hepatic encephalopathy treatment and liver detoxification supplements.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "l-phenylalanine", name: "L-Phenylalanine", cas: "63-91-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An essential amino acid precursor to tyrosine, dopamine, and norepinephrine, used in mood and pain support.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "l-proline", name: "L-Proline", cas: "147-85-3", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A non-essential amino acid critical for collagen synthesis, skin health, and joint tissue support.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "l-pyroglutamic-acid", name: "L-Pyroglutamic Acid", cas: "98-84-5", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A cyclic derivative of glutamic acid used in cognitive health supplements and skin hydration products.", applications: ["nutraceuticals"] },
  { slug: "l-serine", name: "L-Serine", cas: "56-45-1", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A non-essential amino acid involved in neurotransmitter synthesis and phospholipid production for brain health.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "l-theanine", name: "L-Theanine", cas: "3081-61-6", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An amino acid found in green tea, used for relaxation, focus, and stress reduction without sedation.", applications: ["nutraceuticals"] },
  { slug: "l-threonine", name: "L-Threonine", cas: "72-19-5", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An essential amino acid important for immune function, gut health, and collagen/elastin production.", applications: ["animal-nutrition", "nutraceuticals"] },
  { slug: "l-tryptophan", name: "L-Tryptophan", cas: "73-22-3", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "An essential amino acid precursor to serotonin and melatonin, used in sleep and mood support supplements.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "l-tyrosine", name: "L-Tyrosine", cas: "60-18-4", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A non-essential amino acid precursor to catecholamines, used in cognitive and stress support formulations.", applications: ["nutraceuticals", "sports-nutrition", "pharmaceuticals"] },
  { slug: "l-valine", name: "L-Valine", cas: "72-18-4", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A branched-chain essential amino acid used in sports nutrition for muscle recovery and energy production.", applications: ["sports-nutrition", "animal-nutrition", "nutraceuticals"] },
  { slug: "n-acetyl-l-tyrosine", name: "N-Acetyl L-Tyrosine", cas: "537-55-3", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "A more soluble form of tyrosine used in cognitive enhancement, stress adaptation, and neurotransmitter support.", applications: ["nutraceuticals", "sports-nutrition"] },
  { slug: "n-acetyl-l-carnitine", name: "N-Acetyl L-Carnitine", cas: "14992-62-2", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "ALCAR, a form of carnitine that crosses the blood-brain barrier, used in brain health and energy metabolism.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "n-acetyl-l-cysteine", name: "N-Acetyl L-Cysteine", cas: "616-91-1", categorySlug: "amino-acids", categoryTitle: "Amino Acids", description: "NAC, a powerful antioxidant precursor to glutathione, used in respiratory health and liver support supplements.", applications: ["pharmaceuticals", "nutraceuticals"] },



  // === HERBAL EXTRACTS (7 products) ===
  { slug: "5-htp", name: "5-HTP", cas: "56-69-9", categorySlug: "herbal-extracts", categoryTitle: "Herbal Extracts", description: "A naturally occurring amino acid precursor to serotonin, derived from Griffonia simplicifolia seeds for mood and sleep support.", applications: ["nutraceuticals"] },
  { slug: "ginseng-extract", name: "Ginseng Extract", cas: "90045-38-8", categorySlug: "herbal-extracts", categoryTitle: "Herbal Extracts", description: "Standardised Panax ginseng extract with consistent ginsenoside content for energy, immunity, and cognitive support.", applications: ["nutraceuticals"] },
  { slug: "grape-seed-extract", name: "Grape Seed Extract", cas: "84929-27-1", categorySlug: "herbal-extracts", categoryTitle: "Herbal Extracts", description: "Rich in proanthocyanidins and oligomeric procyanidins, used for antioxidant support and cardiovascular health.", applications: ["nutraceuticals"] },
  { slug: "quercetin", name: "Quercetin", cas: "117-39-5", categorySlug: "herbal-extracts", categoryTitle: "Herbal Extracts", description: "A flavonoid antioxidant with anti-inflammatory properties, used in immune support and allergy relief formulations.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "resveratrol", name: "Resveratrol", cas: "501-36-0", categorySlug: "herbal-extracts", categoryTitle: "Herbal Extracts", description: "A polyphenolic compound from Japanese knotweed, used in longevity, cardiovascular, and antioxidant supplements.", applications: ["nutraceuticals"] },
  { slug: "rutin", name: "Rutin", cas: "153-18-4", categorySlug: "herbal-extracts", categoryTitle: "Herbal Extracts", description: "A bioflavonoid glycoside that strengthens capillaries and supports vascular health, often combined with vitamin C.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "silymarin-80", name: "Silymarin 80%", cas: "65666-07-1", categorySlug: "herbal-extracts", categoryTitle: "Herbal Extracts", description: "Standardised milk thistle extract with 80% silymarin content, used for liver health and detoxification support.", applications: ["nutraceuticals", "pharmaceuticals"] },

  // === NUTRACEUTICALS (23 products) ===
  { slug: "adenine", name: "Adenine", cas: "73-24-5", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A purine base used in cell culture media, energy metabolism research, and specialty supplement formulations.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "adenosine-triphosphate", name: "Adenosine Triphosphate", cas: "56-65-5", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "The primary energy currency of cells, used in research, cell culture, and specialty metabolic support products.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "agmatine-sulfate", name: "Agmatine Sulfate", cas: "2482-00-0", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A neuromodulator derived from arginine decarboxylation, used in sports nutrition and cognitive health supplements.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "alanyl-glutamine", name: "Alanyl Glutamine", cas: "39537-23-0", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A dipeptide form of glutamine with superior stability and absorption, used in clinical nutrition and gut health.", applications: ["pharmaceuticals", "nutraceuticals", "sports-nutrition"] },
  { slug: "ara-10", name: "ARA 10%", cas: "506-32-1", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Arachidonic acid oil at 10% concentration, essential for infant brain development and inflammatory response.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "betaine-hcl", name: "Betaine HCL", cas: "590-46-5", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Betaine hydrochloride used for digestive acid support, methylation, and homocysteine metabolism.", applications: ["nutraceuticals", "sports-nutrition"] },
  { slug: "carnosine", name: "Carnosine", cas: "305-84-0", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A dipeptide with anti-glycation and antioxidant properties, used in anti-aging and muscle endurance supplements.", applications: ["nutraceuticals", "sports-nutrition"] },
  { slug: "choline-bitartarate", name: "Choline Bitartarate", cas: "87-67-2", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A stable choline source supporting brain health, liver function, and neurotransmitter synthesis.", applications: ["nutraceuticals", "sports-nutrition"] },
  { slug: "coenzyme-q10", name: "Coenzyme Q10", cas: "303-98-0", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A vital mitochondrial antioxidant for cellular energy production, heart health, and anti-aging formulations.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "conjugated-linoleic-acid-cla-60", name: "Conjugated Linoleic Acid (CLA 60%)", cas: "2420-56-6", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A 60% CLA oil blend used for body composition management and metabolic health support.", applications: ["nutraceuticals", "sports-nutrition"] },
  { slug: "creatine-hcl", name: "Creatine HCL", cas: "17050-09-8", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Creatine hydrochloride with higher solubility than monohydrate, used in compact sports nutrition formulations.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "creatine-malate", name: "Creatine Malate", cas: "177024-88-5", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Creatine bound to malic acid for enhanced absorption and reduced water retention in performance supplements.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "creatine-nitrate", name: "Creatine Nitrate", cas: "82516-64-5", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Creatine nitrate combining creatine's performance benefits with nitrate's vasodilation properties.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "dha-10", name: "DHA 10%", cas: "6217-54-5", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Docosahexaenoic acid at 10% concentration, essential for brain, eye, and cardiovascular health support.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "dmae-bitartarate", name: "DMAE Bitartarate", cas: "5988-51-2", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Dimethylaminoethanol bitartrate used in cognitive support, focus enhancement, and anti-aging skincare.", applications: ["nutraceuticals"] },
  { slug: "epa-10", name: "EPA 10%", cas: "10417-94-4", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "Eicosapentaenoic acid at 10% concentration, supporting heart health, inflammation balance, and joint function.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "gamma-aminobutyric-acid-gaba", name: "Gamma Aminobutyric Acid (GABA)", cas: "56-12-2", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "The primary inhibitory neurotransmitter, used in relaxation, sleep quality, and stress management supplements.", applications: ["nutraceuticals"] },
  { slug: "glutathione", name: "Glutathione", cas: "70-18-8", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "The master antioxidant tripeptide, used in skin brightening, detoxification, and immune support formulations.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "melatonin", name: "Melatonin", cas: "73-31-4", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A pineal hormone regulating circadian rhythm, used in sleep support and jet lag management supplements.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "methylsulfonylmethane-msm", name: "Methylsulfonylmethane (MSM)", cas: "67-71-0", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "An organic sulfur compound supporting joint health, collagen production, and inflammatory response balance.", applications: ["nutraceuticals", "sports-nutrition"] },
  { slug: "palmitoylethanolamide", name: "Palmitoylethanolamide", cas: "544-31-0", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "An endogenous fatty acid amide with pain-modulating and anti-inflammatory properties for nerve health.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "s-adenosyl-methionine-same", name: "S-Adenosyl Methionine (SAMe)", cas: "29908-03-0", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "A methyl donor involved in neurotransmitter synthesis, liver function, and joint cartilage support.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "sodium-hyaluronate", name: "Sodium Hyaluronate", cas: "9067-32-7", categorySlug: "nutraceuticals", categoryTitle: "Nutraceuticals", description: "The sodium salt of hyaluronic acid used in joint health, skin hydration, and eye care formulations.", applications: ["nutraceuticals", "pharmaceuticals"] },

  // === SWEETENERS (11 products) ===
  { slug: "acesulfame-k", name: "Acesulfame K", cas: "55589-62-3", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A zero-calorie artificial sweetener 200 times sweeter than sugar, stable under heat for baking and beverages.", applications: ["pharmaceuticals"] },
  { slug: "allulose", name: "Allulose", cas: "551-68-8", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A rare natural sugar with 70% sweetness of sucrose but minimal caloric impact, keto-friendly formulation.", applications: ["nutraceuticals"] },
  { slug: "aspartame", name: "Aspartame", cas: "22839-47-0", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A low-calorie artificial sweetener 200 times sweeter than sucrose, widely used in diet beverages and foods.", applications: ["pharmaceuticals"] },
  { slug: "erythritol", name: "Erythritol", cas: "149-32-6", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A sugar alcohol with zero calories and no glycemic impact, ideal for keto and diabetic-friendly products.", applications: ["pharmaceuticals"] },
  { slug: "mannitol", name: "Mannitol", cas: "69-65-8", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A sugar alcohol used as a sweetener, humectant, and osmotic diuretic in pharma and food applications.", applications: ["pharmaceuticals"] },
  { slug: "neotame", name: "Neotame", cas: "165450-17-9", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "An ultra-high-intensity sweetener 7000-13000 times sweeter than sugar, heat stable for diverse applications.", applications: ["pharmaceuticals"] },
  { slug: "potassium-sorbate", name: "Potassium Sorbate", cas: "24634-61-5", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A food preservative inhibiting mold and yeast growth, used in beverages, baked goods, and cosmetics.", applications: [] },
  { slug: "sorbic-acid", name: "Sorbic Acid", cas: "110-44-1", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A natural preservative derived from mountain ash berries, used for antimicrobial protection in foods.", applications: [] },
  { slug: "sucralose", name: "Sucralose", cas: "56038-13-2", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A zero-calorie sweetener 600 times sweeter than sugar, heat stable and widely used in processed foods.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "trehalose", name: "Trehalose", cas: "99-20-7", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A natural disaccharide with mild sweetness, used as a stabilizer in pharma and a sugar substitute in foods.", applications: ["pharmaceuticals"] },
  { slug: "xylitol", name: "Xylitol", cas: "87-99-0", categorySlug: "sweeteners", categoryTitle: "Sweeteners", description: "A natural sugar alcohol from birch trees, dental-friendly sweetener with 40% fewer calories than sugar.", applications: ["pharmaceuticals"] },

  // === NUCLEOTIDES (10 products) ===
  { slug: "adenosine", name: "Adenosine", cas: "58-61-7", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "A nucleoside involved in energy transfer and cellular signaling, used in research and specialty formulations.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "b-nicotinamide-mononucleotide", name: "B-Nicotinamide Mononucleotide", cas: "1094-61-7", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "A direct NAD+ precursor supporting cellular energy, DNA repair, and longevity-focused supplement formulations.", applications: ["nutraceuticals"] },
  { slug: "cytidine", name: "Cytidine", cas: "65-46-3", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "A pyrimidine nucleoside used in RNA synthesis research and specialty cognitive health formulations.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "ergothioneine", name: "Ergothioneine", cas: "497-30-3", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "A naturally occurring amino acid antioxidant from mushrooms, protecting mitochondria from oxidative damage.", applications: ["nutraceuticals"] },
  { slug: "guanosine", name: "Guanosine", cas: "118-00-3", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "A purine nucleoside used in research, cell culture, and specialty neurological health formulations.", applications: ["pharmaceuticals", "nutraceuticals"] },
  { slug: "inosine", name: "Inosine", cas: "58-63-9", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "A purine nucleoside supporting ATP production during exercise and nerve regeneration research.", applications: ["sports-nutrition", "nutraceuticals", "pharmaceuticals"] },
  { slug: "nicotinamide-adenine-dinucleotide", name: "Nicotinamide Adenine Dinucleotide", cas: "53-84-9", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "NAD, a coenzyme central to cellular metabolism, redox reactions, and energy production pathways.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "nicotinamide-mononucleotide", name: "Nicotinamide Mononucleotide", cas: "1094-61-7", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "NMN, a key NAD+ biosynthesis intermediate for cellular energy, sirtuin activation, and healthy aging.", applications: ["nutraceuticals"] },
  { slug: "nicotinamide-riboside-chloride", name: "Nicotinamide Riboside Chloride", cas: "23111-00-4", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "NR chloride, a bioavailable NAD+ precursor supporting mitochondrial function and metabolic health.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "uridine", name: "Uridine", cas: "58-96-8", categorySlug: "nucleotides", categoryTitle: "Nucleotides", description: "A pyrimidine nucleoside supporting RNA synthesis, cognitive function, and cellular membrane health.", applications: ["nutraceuticals", "pharmaceuticals"] },

  // === PROTEINS (4 products) ===
  { slug: "pea-protein", name: "Pea Protein", cas: "N/A", categorySlug: "proteins", categoryTitle: "Proteins", description: "A hypoallergenic plant protein with complete amino acid profile, ideal for vegan and allergen-free formulations.", applications: ["sports-nutrition", "animal-nutrition"] },
  { slug: "soy-protein-isolate", name: "Soy Protein Isolate", cas: "N/A", categorySlug: "proteins", categoryTitle: "Proteins", description: "A high-quality plant protein with 90% protein content, ideal for sports nutrition and food applications.", applications: ["sports-nutrition", "pharmaceuticals"] },
  { slug: "whey-protein-concentrate", name: "Whey Protein Concentrate", cas: "N/A", categorySlug: "proteins", categoryTitle: "Proteins", description: "A cost-effective dairy protein with 35-80% protein content, widely used in sports nutrition and food fortification.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "whey-protein-80-instant", name: "Whey Protein 80% Instant", cas: "N/A", categorySlug: "proteins", categoryTitle: "Proteins", description: "An instantized whey protein concentrate with 80% protein content and superior solubility for shakes and smoothies.", applications: ["sports-nutrition", "nutraceuticals"] },

  // === SPORTS NUTRITION (5 products) ===
  { slug: "bcaa-211-411-811", name: "BCAA 2:1:1/4:1:1/8:1:1", cas: "N/A", categorySlug: "sports-nutrition", categoryTitle: "Sports Nutrition", description: "Branched-chain amino acid ratios tailored for muscle protein synthesis, recovery, and endurance performance.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "beta-alanine", name: "Beta Alanine", cas: "107-95-9", categorySlug: "sports-nutrition", categoryTitle: "Sports Nutrition", description: "A non-essential amino acid that buffers lactic acid buildup, extending muscular endurance during high-intensity exercise.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "betaine-anhydrous", name: "Betaine Anhydrous", cas: "107-43-7", categorySlug: "sports-nutrition", categoryTitle: "Sports Nutrition", description: "Trimethylglycine supporting cellular hydration, power output, and homocysteine metabolism in athletes.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "creatine-monohydrate", name: "Creatine Monohydrate", cas: "6020-87-7", categorySlug: "sports-nutrition", categoryTitle: "Sports Nutrition", description: "The most researched sports supplement, increasing ATP regeneration for strength, power, and muscle mass gains.", applications: ["sports-nutrition", "nutraceuticals"] },
  { slug: "eaa-essential-amino-acid", name: "EAA (Essential Amino Acid)", cas: "N/A", categorySlug: "sports-nutrition", categoryTitle: "Sports Nutrition", description: "A complete blend of all nine essential amino acids for maximum muscle protein synthesis and recovery.", applications: ["sports-nutrition", "nutraceuticals"] },

  // === VITAMINS (9 products) ===
  { slug: "biotin", name: "Biotin", cas: "58-85-5", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "Vitamin B7/H supporting hair, skin, nail health, and carboxylase enzyme function in metabolism.", applications: ["nutraceuticals"] },
  { slug: "calcium-d-pantothenate-vitamin-b5", name: "Calcium D Pantothenate (Vitamin B5)", cas: "137-08-6", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "Vitamin B5 essential for Coenzyme A synthesis, energy metabolism, and skin health formulations.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "inositol-vitamin-b8", name: "Inositol (Vitamin B8)", cas: "87-89-8", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "A carbocyclic sugar involved in cell signaling, mood regulation, and insulin sensitivity support.", applications: ["nutraceuticals", "pharmaceuticals"] },
  { slug: "vitamin-a-acetate-325-500-cws", name: "Vitamin A Acetate 325/500 cws", cas: "142-79-0", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "Cold water soluble Vitamin A acetate beadlets at 325,000 or 500,000 IU/g for feed and food fortification.", applications: ["animal-nutrition", "nutraceuticals"] },
  { slug: "vitamin-a-palmitate-250-500-cws", name: "Vitamin A Palmitate 250/500 cws", cas: "79-81-2", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "Cold water soluble Vitamin A palmitate beadlets at 250,000 or 500,000 IU/g for stable vitamin A delivery.", applications: ["animal-nutrition", "nutraceuticals"] },
  { slug: "vitamin-d2-100-500-cws", name: "Vitamin D2 100/500 cws", cas: "50-14-6", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "Ergocalciferol beadlets at 100,000 or 500,000 IU/g for bone health and calcium absorption support.", applications: ["nutraceuticals", "animal-nutrition"] },
  { slug: "vitamin-d3-100-500-cws", name: "Vitamin D3 100/500 cws", cas: "67-97-0", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "Cholecalciferol beadlets at 100,000 or 500,000 IU/g, the preferred form for vitamin D supplementation.", applications: ["nutraceuticals", "animal-nutrition"] },
  { slug: "vitamin-e-50", name: "Vitamin E 50%", cas: "10191-41-0", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "dl-alpha-tocopheryl acetate at 50% CWS/S/O for antioxidant protection and skin health applications.", applications: ["nutraceuticals", "animal-nutrition"] },
  { slug: "vitamin-k1-5-10", name: "Vitamin K1 5% 10%", cas: "84-80-0", categorySlug: "vitamins", categoryTitle: "Vitamins", description: "Phylloquinone (Vitamin K1) at 5% or 10% CWS for blood clotting support and bone mineralization.", applications: ["nutraceuticals", "pharmaceuticals"] },
];

export function getProductBySlug(slug: string): IndividualProduct | undefined {
  return individualProducts.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug: string): IndividualProduct[] {
  return individualProducts.filter((p) => p.categorySlug === categorySlug);
}

export function getAllProducts(): IndividualProduct[] {
  return individualProducts;
}

export const totalProductCount = individualProducts.length;
